### ISSUE TITLE
Inner classes throws InstantiationException 

### ISSUE THREAD

**Issue by TryHardDood** [CubeEngine/ReflecT#29]
## Stacktrace:
```
de.cubeisland.engine.reflect.exception.ReflectedInstantiationException: Failed to create an instance of hu.tryharddood.advancedkits.Kit$KitConfig
        at de.cubeisland.engine.reflect.Reflector.create(Reflector.java:128) ~[?:?]
        at de.cubeisland.engine.reflect.Reflector.load(Reflector.java:70) ~[?:?]
        at de.cubeisland.engine.reflect.Reflector.load(Reflector.java:87) ~[?:?]
        at hu.tryharddood.advancedkits.Kit.<init>(Kit.java:34) ~[?:?]
        at hu.tryharddood.advancedkits.KitManager.loadKits(KitManager.java:53) ~[?:?]
        at hu.tryharddood.advancedkits.AdvancedKits.onEnable(AdvancedKits.java:42) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-65a0347-a552117]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-65a0347-a552117]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-65a0347-a552117]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-65a0347-a552117]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.11.2.jar:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.11.2.jar:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.11.2.jar:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-65a0347-a552117]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-65a0347-a552117]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.InstantiationException: hu.tryharddood.advancedkits.Kit$KitConfig
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_121]
        at de.cubeisland.engine.reflect.Reflector.create(Reflector.java:118) ~[?:?]
        ... 16 more
Caused by: java.lang.NoSuchMethodException: hu.tryharddood.advancedkits.Kit$KitConfig.<init>()
        at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_121]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_121]
        at de.cubeisland.engine.reflect.Reflector.create(Reflector.java:118) ~[?:?]
        ... 16 more
```

## Code:
```
public class Kit
{
	private KitConfig config;

	public Kit(String name)
	{
		this.config = instance.factory.load(KitConfig.class, getSaveFile());
		this.config.reload();
		this.config.save();
	}

	public File getSaveFile()
	{
		File file = new File(instance.getDataFolder() + File.separator + "kits", "test" + ".yml");
		if (!instance.getDataFolder().exists()) {
			instance.getDataFolder().mkdir();
		}
		if (!file.exists()) {
			try {
				file.createNewFile();
			}
			catch (IOException e) {
				instance.getLogger().info("Couldn't create the savefile for " + "test");
				instance.getLogger().info(" -- StackTrace --");
				e.printStackTrace();
				instance.getLogger().info(" -- End of StackTrace --");
			}
		}
		return file;
	}

	public void save()
	{
		this.config.save();
	}

	public KitConfig getConfig()
	{
		return this.config;
	}

	public class KitConfig extends ReflectedYaml
	{
		@Name("Flags")
		public Flags flags;

		public class Flags implements Section
		{
			@Comment("Should players see this kit in the gui?")
			public boolean visible        = true;
		}
}
```

**Comment by Faithcaio** [comment]
You proably need to make your inner class static.
Or just move it in a separate class.

**Comment by TryHardDood** [comment]
Could this fix the problem?
https://gist.github.com/TryHardDood/d858ef87c6d207e919698e003f9e3dcf

I can't make the inner class static because I need to access the parent class too.

**Comment by Faithcaio** [comment]
You would need to pass an instnace of the parent class.

**Comment by TryHardDood** [comment]
For that the `clazz.getSuperclass().newInstance()` does not work?

**Comment by Faithcaio** [comment]
could work but its another instance of you parent class

**Comment by TryHardDood** [comment]
I see

**Comment by TryHardDood** [comment]
So this would work?
https://gist.github.com/TryHardDood/d858ef87c6d207e919698e003f9e3dcf#file-reflector-java-L146

**Comment by Faithcaio** [comment]
looks fine

**Comment by TryHardDood** [comment]
How can I deploy to maven? ( Which command? )
I set up a private server but when I deploy it only uploads the modules.
